language: python
python:
 - "2.7"
install:
 - pip install -U -i https://pypi.doubanio.com/simple pip setuptools wheel
 - pip install -r requirements.txt -i https://pypi.doubanio.com/simple
 - pip install coveralls 
before_install:
 - mysql -e 'create database testd;'
services:
 - mysql
script: python setup.py test 
after_success:
 - coveralls
